---
name:   Geometry CUGL Exploration              
short:  Geometry                    
appid:  edu.cornell.gdiac.code2     # Application identifier for Mac, iOS, Android
suffix: GDBBC96B

build:  build                       
assets: assets                      
icon:   icon.png

orientation: landscape              

sources:                            
    - source/*.cpp
    - source/*.h

modules:
    - physics2
    - scene2


targets:                       
    - android                   
    - apple                     
    - windows                   
    - cmake                     
